#!/bin/bash
#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=analysis
#SBATCH --output=analysis_%j.out
#SBATCH --array=0-5

# Program name and its flags
PROGRAM=mpi_mat_vect_lines
FLAGS=

# Inputs
ARGS=($(<mat.txt))
ARG=${ARGS[${SLURM_ARRAY_TASK_ID}]}

# Factor of the problem size
FACTOR=100

# How many times the program will be executed
COUNT=5

PROCESSES=(1 2 4 8 16 32)

for p in "${PROCESSES[@]}"; do
	for i in $(seq $COUNT); do
		mpirun -np $p $PROGRAM $FLAGS $(($ARG * $FACTOR)) $(($ARG))
	done
done
