#!/bin/bash

#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=2
#SBATCH --time=0-0:5
#SBATCH --job-name=ping_pong
#SBATCH --output=ping_pong_%j.out
#SBATCH --array=0-1

if [ "${SLURM_ARRAY_TASK_ID}" -eq 0 ] 
then
	echo "Measuring with clock"
	mpirun mpi_pp_clock
else
	echo "Measuring with wtime"
	mpirun mpi_pp_wtime
fi
