#!/bin/bash
#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=trap
#SBATCH --output=trap_time_%j.out
#SBATCH --array=0-5

ARGS=($(<inputs.txt))

ARG=${ARGS[${SLURM_ARRAY_TASK_ID}]}

FACTOR=1000000

COUNT=5

for p in "${ARGS[@]}"; do
	for i in $(seq $COUNT); do
		mpirun -np $p mpi_trap_time $(($ARG * $FACTOR))
	done
done
