#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Error: Please provide the number of processs."
    exit 1
fi

echo "Original execution:"
mpiexec --oversubscribe -n $1 ./mpi_hello

echo \

echo "Without +1:"
mpiexec --oversubscribe -n $1 ./mpi_hello_without_eof

echo \

echo "Using MAX_STRING:"
mpiexec --oversubscribe -n $1 ./mpi_hello_max_string

