#!/bin/bash

#SBATCH --partition=intel-128
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=ping_pong
#SBATCH --output=ping_pong_%j.out
#SBATCH --array=0-1

if [SLURM_ARRAY_TASK_ID -eq 0]
then
    echo "With clock:"
    mpirun mpi_pp_clock
else
    echo "With Wtime:"
    mpirun mpi_pp_wtime
done

