#!/bin/bash
#SBATCH --partition gpu-4-a100 
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name heat
#SBATCH --output heat-%j.out

echo "Sequential version:"
./heat 8000 10

echo "Parallel version:"
./heat_gpu 8000 10
