#!/bin/bash
#SBATCH --partition gpu-4-a100 
#SBATCH --nodes 1
#SBATCH --time 00:02:00
#SBATCH --job-name vadd
#SBATCH --output vadd-%j.out

echo "Sequential version:"
./vadd

echo "Parallel version (CPU):"
./vadd_p

echo "Parallel version (GPU):"
OMP_TARGET_OFFLOAD=MANDATORY ./vadd_p_gpu
