#!/bin/bash
#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=odd_even
#SBATCH --output=odd_even_time-%j.out
#SBATCH --array=1-5

ARGS=($(<inputs.txt))
ARG=${ARGS[${SLURM_ARRAY_TASK_ID}]}

echo $ARG

# srun mpi_odd_even_time g $ARG
