#!/bin/bash
#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=odd_even
#SBATCH --output=odd_even_time-%j.out

N=1000000

srun submit_odd_even_time g $N