#!/bin/bash
#SBATCH --partition=amd-512
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=hello
#SBATCH --output=hello-%j.out

# Run on supercomputer
srun mpi_hello