#!/bin/bash
#SBATCH --partition=intel-128
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=4
#SBATCH --time=0-0:5
#SBATCH --job-name=odd_even
#SBATCH --output=odd_even-%j.out

srun mpi_odd_even g 100
