#!/bin/bash
#SBATCH --partition=amd-512
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --time=0-0:5
#SBATCH --job-name=trap1
#SBATCH --output=trap1-%j.out

# Run the original version
time srun mpi_trap1

# Run the version with ANY_SOURCE tag
time srun mpi_trap1_any_source

# Note: 
#   The second version run faster because proccess 0
#   receives data from any process that is done with 
#   the sum
